image: openjdk:16

build_and_publish_snapshot:
  except:
    - master
  script:
    - ./gradlew clean build publish

build_and_publish_release:
  only:
    - master
  script:
    - ./gradlew -Psnapshot=false clean build publish closeAndReleaseRepository
