image: openjdk:16

build:
  except:
    - master
    - /^release-.*$/
  script:
    - ./gradlew clean build

build_and_publish_snapshot:
  only:
    - master
  script:
    - ./gradlew clean build publish

build_and_publish_release:
  only:
    - /^release-.*$/
  script:
    - ./gradlew -Psnapshot=false clean build publish closeAndReleaseRepository
